

run:
	#../../node_modules/.bin/ts-node JackCompiler.ts Seven/Main.jack
	#../../node_modules/.bin/ts-node JackCompiler.ts Pong/Bat.jack
	#../../node_modules/.bin/ts-node JackCompiler.ts Pong/PongGame.jack
	../../node_modules/.bin/ts-node JackCompiler.ts Pong/Ball.jack
